added k switch for insecure certs
SReject/JSON-For-Mirc pull request #52
Opened 2020-01-04 21:10 UTC by silv3rr

Hi @SReject,

Thanks for JFM, i've used it in 2 scripts now and works nicely. I also like how in the new versions the JS part is formatted in seperate file.

For an API on localhost with selfsigned cert I got a (expected) cert error "The certificate authority is invalid or incorrect".
I could not find an option to disable cert checking so a I added a "k" switch to JSONOpen (like curl -k).

The Tests script passed and I've added tests for -k without -u" switch and 2 for JSONOpen and a known bad cert with/without "-k".

2020-01-04 23:06 UTC, SReject commented
Merge latest upstream please

2020-01-05 00:46 UTC, SReject requested changes
Along with these:

Merge upstream, giving upstream precedence
Bump build version `1.1.xxxx`

2020-01-05 00:46 UTC, SReject commented on test/JSON for mIRC - Tests.mrc
> +      halt
Don't halt, instead return the warning as though its an error

2020-01-05 00:46 UTC, SReject commented on src/JSON For mIRC.mrc
> +;;     -k:  Used with -u; Ignore all certificate errors
use `-i` (for insecure) over `-k`

2020-01-05 00:46 UTC, SReject commented on src/JSON For mIRC.js
> +    JSONCreate = function(type, source, parse, insecure) {
Not sure how this occured, but this should be `root.JSONCreate = ...`

2020-01-05 21:00 UTC, silv3rr commented
Applied required changes and fixed merge issues

2020-01-05 22:20 UTC, SReject approved these changes

2020-01-05 22:23 UTC, merged

2020-01-05 22:41 UTC, SReject commented
Merged, thanks for the help!